// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(badge).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component } from '@angular/core';import { HlmBadgeDirective } from '@spartan-ng/helm/badge';@Component({
	selector: 'spartan-badge-preview',
	imports: [HlmBadgeDirective],
	template: \`
		<a target="_blank" href="https://github.com/goetzrobin/spartan" hlmBadge>This is madness. This is spartan.</a>
	\`,
})
export class BadgePreviewComponent {}
`;
