export type ComponentRoute = {
	label: string;
	url: string;
	wip?: boolean;
	new?: boolean;
};

export const components: ComponentRoute[] = [
	{ label: 'Accordion', url: '/accordion' },
	{ label: 'Alert', url: '/alert' },
	{ label: 'Alert Dialog', url: '/alert-dialog' },
	{ label: 'Aspect Ratio', url: '/aspect-ratio' },
	{ label: 'Autocomplete', url: '/autocomplete' },
	{ label: 'Avatar', url: '/avatar' },
	{ label: 'Badge', url: '/badge' },
	{ label: 'Breadcrumb', url: '/breadcrumb' },
	{ label: 'Button', url: '/button' },
	{ label: 'Calendar', url: '/calendar' },
	{ label: 'Card', url: '/card' },
	{ label: 'Carousel', url: '/carousel' },
	{ label: 'Checkbox', url: '/checkbox' },
	{ label: 'Collapsible', url: '/collapsible' },
	{ label: 'Combobox', url: '/combobox' },
	{ label: 'Command', url: '/command' },
	{ label: 'Context Menu', url: '/context-menu' },
	{ label: 'Data Table', url: '/data-table' },
	{ label: 'Date Picker', url: '/date-picker' },
	{ label: 'Dialog', url: '/dialog' },
	{ label: 'Dropdown Menu', url: '/dropdown-menu' },
	{ label: 'Form', url: '/form', wip: true },
	{ label: 'Form Field', url: '/form-field' },
	{ label: 'Hover Card', url: '/hover-card' },
	{ label: 'Icon', url: '/icon' },
	{ label: 'Input', url: '/input' },
	{ label: 'Input Group', url: '/input-group', new: true },
	{ label: 'Input OTP', url: '/input-otp' },
	{ label: 'Kbd', url: '/kbd', new: true },
	{ label: 'Label', url: '/label' },
	{ label: 'Menubar', url: '/menubar' },
	{ label: 'Navigation Menu', url: '/navigation-menu', wip: true },
	{ label: 'Pagination', url: '/pagination' },
	{ label: 'Popover', url: '/popover' },
	{ label: 'Progress', url: '/progress' },
	{ label: 'Radio Group', url: '/radio-group' },
	{ label: 'Scroll Area', url: '/scroll-area' },
	{ label: 'Select', url: '/select' },
	{ label: 'Separator', url: '/separator' },
	{ label: 'Sheet', url: '/sheet' },
	{ label: 'Sidebar', url: '/sidebar', new: true },
	{ label: 'Skeleton', url: '/skeleton' },
	{ label: 'Slider', url: '/slider' },
	{ label: 'Sonner (Toast)', url: '/sonner' },
	{ label: 'Spinner', url: '/spinner' },
	{ label: 'Switch', url: '/switch' },
	{ label: 'Table', url: '/table' },
	{ label: 'Tabs', url: '/tabs' },
	{ label: 'Textarea', url: '/textarea' },
	{ label: 'Toggle', url: '/toggle' },
	{ label: 'Toggle Group', url: '/toggle-group' },
	{ label: 'Tooltip', url: '/tooltip' },
];
