// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(calendar).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component } from '@angular/core';import { HlmCalendarComponent } from '@spartan-ng/helm/calendar';@Component({
	selector: 'spartan-calendar-preview',
	imports: [HlmCalendarComponent],
	template: \`
		<hlm-calendar [(date)]="selectedDate" [min]="minDate" [max]="maxDate" />
	\`,
	host: {
		class: 'preview flex min-h-[350px] w-full justify-center p-10 items-center',
	},
})
export class CalendarPreviewComponent {
	/** The selected date */
	public selectedDate = new Date();

	/** The minimum date */
	public minDate = new Date(2023, 0, 1);

	/** The maximum date */
	public maxDate = new Date(2030, 11, 31);
}
`;
