// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(calendar).preview.ts` file or the generator itself.
Run `pnpm run generate-snippets` to update this file.
*/

export const calendarMultipleCode = `
import { Component } from '@angular/core';
import { HlmCalendarMultiComponent } from '@spartan-ng/helm/calendar';

@Component({
	selector: 'spartan-calendar-multiple',
	imports: [HlmCalendarMultiComponent],
	template: \`
		<hlm-calendar-multi
			[(date)]="selectedDates"
			[min]="minDate"
			[max]="maxDate"
			[minSelection]="2"
			[maxSelection]="6"
		/>
	\`,
	host: {
		class: 'preview flex min-h-[350px] w-full justify-center p-10 items-center',
	},
})
export class CalendarMultipleExampleComponent {
	/** The selected date */
	public selectedDates = [new Date()];

	/** The minimum date */
	public minDate = new Date(2023, 0, 1);

	/** The maximum date */
	public maxDate = new Date(2030, 11, 31);
}

export const calendarMultipleCode = \`
import { Component } from '@angular/core';
import { HlmCalendarMultiComponent } from '@spartan-ng/helm/calendar';

@Component({
	selector: 'spartan-calendar-multiple',
	imports: [HlmCalendarMultiComponent],
	template: \\`
		<hlm-calendar-multi
			[(date)]="selectedDates"
			[min]="minDate"
			[max]="maxDate"
			[minSelection]="2"
			[maxSelection]="6"
		/>
	\\`,
	host: {
		class: 'preview flex min-h-[350px] w-full justify-center p-10 items-center',
	},
})
export class CalendarMultipleExampleComponent {
	/** The selected date */
	public selectedDates = [new Date()];

	/** The minimum date */
	public minDate = new Date(2023, 0, 1);

	/** The maximum date */
	public maxDate = new Date(2030, 11, 31);
}
\`;
`;

export const defaultCode = `
import { Component } from '@angular/core';
import { HlmCalendarComponent } from '@spartan-ng/helm/calendar';

@Component({
	selector: 'spartan-calendar-preview',
	imports: [HlmCalendarComponent],
	template: \`
		<hlm-calendar [(date)]="selectedDate" [min]="minDate" [max]="maxDate" />
	\`,
	host: {
		class: 'preview flex min-h-[350px] w-full justify-center p-10 items-center',
	},
})
export class CalendarPreviewComponent {
	/** The selected date */
	public selectedDate = new Date();

	/** The minimum date */
	public minDate = new Date(2023, 0, 1);

	/** The maximum date */
	public maxDate = new Date(2030, 11, 31);
}

export const defaultCode = \`
@Component({
	selector: 'spartan-calendar-preview',
imports: [HlmCalendarComponent],
	template: '<hlm-calendar [(date)]="selectedDate" [min]="minDate" [max]="maxDate" />',
})
export class CalendarPreviewComponent {
	/** The selected date */
	selectedDate = new Date();

	/** The minimum date */
	minDate = new Date(2023, 0, 1);

	/** The maximum date */
	maxDate = new Date(2030, 11, 31);
}
\`;

export const codeSkeleton = \`
<hlm-calendar
	[(date)]="selectedDate"
	[min]="minDate"
	[max]="maxDate"
	[disabled]="false"
	[dateDisabled]="(date) => false"
	[weekStartsOn]="0"
/>
\`;
`;


