// eslint-disable -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(scroll-area).preview.ts` file or the generator itself.
Run `pnpm run generate-snippets` to update this file.
*/

export const defaultCode = `
import { Component } from '@angular/core';
import { HlmScrollAreaDirective } from '@spartan-ng/helm/scroll-area';
import { HlmSeparatorDirective } from '@spartan-ng/helm/separator';
import { NgScrollbarModule } from 'ngx-scrollbar';

@Component({
	selector: 'spartan-scroll-area-preview',
	imports: [HlmSeparatorDirective, HlmScrollAreaDirective, NgScrollbarModule],
	template: \`
		<ng-scrollbar hlm class="border-border h-72 w-48 rounded-md border" visibility="hover">
			<div class="p-4">
				<h4 class="mb-4 text-sm font-medium leading-none">Tags</h4>
				@for (tag of tags; track tag) {
					<div class="text-sm">
						{{ tag }}
						<div hlmSeparator class="my-2"></div>
					</div>
				}
			</div>
		</ng-scrollbar>
	\`,
})
export class ScrollAreaPreviewComponent {
	public tags = Array.from({ length: 50 }).map((_, i, a) => \`v1.2.0-beta.\${a.length - i}\`);
}
`;
