// eslint-disable -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(input).preview.ts` file or the generator itself.
Run `pnpm run generate-snippets` to update this file.
*/

export const inputButtonCode = `
import { Component } from '@angular/core';
import { HlmButtonDirective } from '@spartan-ng/helm/button';
import { HlmInputDirective } from '@spartan-ng/helm/input';

@Component({
	selector: 'spartan-input-button',
	imports: [HlmInputDirective, HlmButtonDirective],
	template: \`
		<div class="flex w-full max-w-sm items-center space-x-2">
			<input aria-label="Email" class="w-80" hlmInput type="email" placeholder="Email" />
			<button hlmBtn variant="outline">Subscribe</button>
		</div>
	\`,
})
export class InputButtonPreviewComponent {}
`;

export const inputDisabledCode = `
import { Component } from '@angular/core';
import { HlmInputDirective } from '@spartan-ng/helm/input';

@Component({
	selector: 'spartan-input-disabled',
	imports: [HlmInputDirective],
	template: \`
		<input class="w-80" hlmInput disabled type="email" placeholder="Email" />
	\`,
})
export class InputDisabledPreviewComponent {}
`;

export const inputFileCode = `
import { Component } from '@angular/core';
import { HlmInputDirective } from '@spartan-ng/helm/input';

@Component({
	selector: 'spartan-input-file',
	imports: [HlmInputDirective],
	template: \`
		<input class="w-80" hlmInput type="file" />
	\`,
})
export class InputFilePreviewComponent {}
`;

export const inputLabelCode = `
import { Component } from '@angular/core';
import { HlmInputDirective } from '@spartan-ng/helm/input';
import { HlmLabelDirective } from '@spartan-ng/helm/label';

@Component({
	selector: 'spartan-input-label',
	imports: [HlmInputDirective, HlmLabelDirective],
	template: \`
		<div class="grid w-full max-w-sm items-center gap-3">
			<label for="email" hlmLabel>Email</label>
			<input hlmInput type="email" id="email" placeholder="Email" />
		</div>
	\`,
})
export class InputLabelPreviewComponent {}
`;

export const defaultCode = `
import { Component } from '@angular/core';
import { HlmInputDirective } from '@spartan-ng/helm/input';

@Component({
	selector: 'spartan-input-preview',
	imports: [HlmInputDirective],
	template: \`
		<input class="w-80" hlmInput type="email" placeholder="Email" />
	\`,
})
export class InputPreviewComponent {}
`;
