// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(spinner).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component } from '@angular/core';import { HlmSpinnerComponent } from '@spartan-ng/helm/spinner';@Component({
	selector: 'spartan-spinner-preview',
	imports: [HlmSpinnerComponent],
	template: \`
		<hlm-spinner />
	\`,
})
export class SpinnerPreviewComponent {}
`;
