import { Injectable, signal } from '@angular/core';

/**
 * Metadata needed to assemble a runnable spartan app on StackBlitz, generated by the
 * `generate-hlm-component-preview` tools generator (so it stays in sync with helm + the CLI).
 * Contains only dependency versions and the Tailwind preset text - never helm component source.
 */
export interface StackBlitzMeta {
	baseDependencies: Record<string, string>;
	devDependencies: Record<string, string>;
	presetCss: string;
}

@Injectable({
	providedIn: 'root',
})
export class StackBlitzMetaService {
	private readonly _meta = signal<StackBlitzMeta | null>(null);

	public readonly meta = this._meta.asReadonly();

	setMeta(meta: StackBlitzMeta): void {
		this._meta.set(meta);
	}
}
