// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(input).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component } from '@angular/core';import { HlmInputDirective } from '@spartan-ng/helm/input';@Component({
	selector: 'spartan-input-preview',
	imports: [HlmInputDirective],
	template: \`
		<input class="w-80" hlmInput type="email" placeholder="Email" />
	\`,
})
export class InputPreviewComponent {}
`;
