// eslint-disable -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(radio-group).preview.ts` file or the generator itself.
Run `pnpm run generate-snippets` to update this file.
*/

export const radioGroupCardCode = `
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideCreditCard } from '@ng-icons/lucide';
import { remixAppleFill, remixPaypalFill } from '@ng-icons/remixicon';
import { hlm } from '@spartan-ng/brain/core';
import { HlmIconDirective } from '@spartan-ng/helm/icon';
import { HlmRadioComponent, HlmRadioGroupComponent } from '@spartan-ng/helm/radio-group';

@Component({
	selector: 'spartan-radio-card-preview',
	providers: [provideIcons({ lucideCreditCard, remixPaypalFill, remixAppleFill })],
	imports: [FormsModule, HlmRadioComponent, HlmRadioGroupComponent, NgIcon, HlmIconDirective],
	template: \`
		<hlm-radio-group class="grid grid-cols-3 gap-4" [(ngModel)]="payment">
			<label class="flex items-center" hlmLabel [class]="cardClass">
				<hlm-radio value="card">
					<ng-icon hlm name="lucideCreditCard" class="mb-3" />
				</hlm-radio>
				Card
			</label>
			<label class="flex items-center" hlmLabel [class]="cardClass">
				<hlm-radio value="paypal">
					<ng-icon hlm name="remixPaypalFill" class="mb-3" />
				</hlm-radio>
				PayPal
			</label>
			<label class="flex items-center" hlmLabel [class]="cardClass">
				<hlm-radio value="apple">
					<ng-icon hlm name="remixAppleFill" class="mb-3" />
				</hlm-radio>
				Apple
			</label>
		</hlm-radio-group>
	\`,
})
export class RadioGroupCardComponent {
	public payment = 'card';

	public readonly cardClass = hlm(
		'block space-x-0 relative',
		// base card styles
		'flex flex-col items-center justify-center py-8 px-4 rounded-lg border-2 border-border',
		// hover and background styles
		'bg-background hover:bg-accent/10 cursor-pointer transition-colors',
		// spacing for the icon and text
		'[&>span]:mt-4',
		// target the checked state properly
		'[&:has([data-checked=true])]:border-2 [&:has([data-checked=true])]:border-primary',
	);
}
`;

export const defaultCode = `
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HlmLabelDirective } from '@spartan-ng/helm/label';
import { HlmRadioComponent, HlmRadioGroupComponent, HlmRadioIndicatorComponent } from '@spartan-ng/helm/radio-group';

@Component({
	selector: 'spartan-radio-group-preview',
	imports: [FormsModule, HlmRadioComponent, HlmRadioIndicatorComponent, HlmRadioGroupComponent, HlmLabelDirective],
	template: \`
		<hlm-radio-group [(ngModel)]="spacing">
			<label class="flex items-center gap-3" hlmLabel>
				<hlm-radio value="default">
					<hlm-radio-indicator indicator />
				</hlm-radio>
				Default
			</label>
			<label class="flex items-center gap-3" hlmLabel>
				<hlm-radio value="comfortable">
					<hlm-radio-indicator indicator />
				</hlm-radio>
				Comfortable
			</label>
			<label class="flex items-center gap-3" hlmLabel>
				<hlm-radio value="compact">
					<hlm-radio-indicator indicator />
				</hlm-radio>
				Compact
			</label>
		</hlm-radio-group>
	\`,
})
export class RadioGroupPreviewComponent {
	public spacing = 'comfortable';
}
`;
