// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(aspect-ratio).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component } from '@angular/core';import { HlmAspectRatioDirective } from '@spartan-ng/helm/aspect-ratio';@Component({
	selector: 'spartan-aspect-ratio-preview',
	imports: [HlmAspectRatioDirective],
	template: \`
		<div class="max-w-xl overflow-hidden rounded-xl drop-shadow">
			<div [hlmAspectRatio]="16 / 9">
				<img alt="Mountain views" src="/assets/mountains.jpg" />
			</div>
		</div>
	\`,
})
export class AspectRatioPreviewComponent {}
`;
