import type { RouteMeta } from '@analogjs/router';
import { Component } from '@angular/core';
import { Code } from '@spartan-ng/app/app/shared/code/code';
import { CodePreview } from '@spartan-ng/app/app/shared/code/code-preview';
import { MainSection } from '@spartan-ng/app/app/shared/layout/main-section';
import { PageBottomNav } from '@spartan-ng/app/app/shared/layout/page-bottom-nav/page-bottom-nav';
import { PageBottomNavLink } from '@spartan-ng/app/app/shared/layout/page-bottom-nav/page-bottom-nav-link';
import { PageNav } from '@spartan-ng/app/app/shared/layout/page-nav/page-nav';
import { SectionIntro } from '@spartan-ng/app/app/shared/layout/section-intro';
import { SectionSubHeading } from '@spartan-ng/app/app/shared/layout/section-sub-heading';
import { metaWith } from '@spartan-ng/app/app/shared/meta/meta.util';
import { HlmAlertImports } from '@spartan-ng/helm/alert';
import { hlmCode, hlmP } from '@spartan-ng/helm/typography';
import { STYLES } from '@spartan-ng/registry';
import { StylesShowcase } from './styles--button-showcase.example';
import { StylesComplexShowcase } from './styles--complex-showcase.example';
import { StylesSelector } from './styles--selector.example';

export const routeMeta: RouteMeta = {
	data: { breadcrumb: 'Styles' },
	meta: metaWith('spartan - Styles', 'Utility classes and styling conventions'),
	title: 'spartan - Styles',
};

@Component({
	selector: 'spartan-styles',
	imports: [
		MainSection,
		SectionIntro,
		PageBottomNav,
		PageBottomNavLink,
		PageNav,
		SectionSubHeading,
		Code,
		HlmAlertImports,
		CodePreview,
		StylesSelector,
		StylesShowcase,
		StylesComplexShowcase,
	],
	template: `
		<section spartanMainSection>
			<spartan-section-intro
				name="Styles"
				lead="Choose a visual style for your components with the style flag in components.json."
			/>

			<p class="${hlmP}">
				The
				<code class="${hlmCode}">style</code>
				flag in
				<code class="${hlmCode}">components.json</code>
				determines the visual appearance of generated components. Each style offers a distinct look while maintaining
				full access to the underlying CSS variables and Tailwind utilities for customization.
			</p>

			<div class="mt-6" hlmAlert>
				<div hlmAlertDescription>
					<p>
						Set the
						<code class="${hlmCode}">style</code>
						field in your
						<code class="${hlmCode}">components.json</code>
						to one of the available options. This affects all components generated by the spartan CLI.
					</p>
				</div>
			</div>

			<spartan-section-sub-heading id="setup">Setup</spartan-section-sub-heading>

			<p class="${hlmP}">
				The style is set the first time you run the spartan CLI. During
				<code class="${hlmCode}">ng g @spartan-ng/cli:init</code>
				or
				<code class="${hlmCode}">ng g @spartan-ng/cli:ui</code>
				you will be prompted to choose a style. The selection is stored in
				<code class="${hlmCode}">components.json</code>
				.
			</p>

			<spartan-code class="mt-6" code="ng g @spartan-ng/cli:init" />

			<spartan-section-sub-heading id="examples">Choose your preferred style</spartan-section-sub-heading>

			<div spartanCodePreview class="border-border mt-4 flex flex-col items-center justify-start gap-4 border">
				<spartan-styles-selector />
				<spartan-styles-complex-showcase />
			</div>

			<div class="border-border mt-4 flex min-h-[350px] items-center justify-start border px-4 lg:px-10">
				<spartan-styles-showcase />
			</div>

			<spartan-section-sub-heading id="switching">Switching styles</spartan-section-sub-heading>

			<p class="${hlmP}">
				To change your style, edit the
				<code class="${hlmCode}">style</code>
				field in
				<code class="${hlmCode}">components.json</code>
				and regenerate affected components:
			</p>

			<spartan-code
				class="mt-6"
				fileName="components.json"
				code='{
  "style": "nova",
  ...
}'
			/>

			<spartan-code class="mt-6" code="ng g @spartan-ng/cli:ui button" />

			<p class="${hlmP}">
				See the
				<a class="font-medium underline" routerLink="/documentation/update-guide#automated-migration">update guide</a>
				for how to migrate existing components to the new style.
			</p>

			<p class="${hlmP}">
				Available styles:
				@for (style of styles; track style; let last = $last) {
					<code class="${hlmCode}">{{ style }}</code>
					@if (!last) {
						,
					} @else {
						.
					}
				}
			</p>

			<spartan-section-sub-heading id="customization">Customization</spartan-section-sub-heading>

			<p class="${hlmP}">
				All styles use the same CSS variable system. After choosing a style, you can further customize colors, border
				radius, and spacing by overriding the CSS variables in your
				<code class="${hlmCode}">styles.css</code>
				file. See the
				<a class="font-medium underline" routerLink="/documentation/theming">Theming</a>
				page for details.
			</p>

			<spartan-section-sub-heading id="icon-sizing">Icon sizing</spartan-section-sub-heading>

			<p class="${hlmP}">
				Icons use
				<code class="${hlmCode}">&lt;ng-icon&gt;</code>
				which inherits its size from the parent font size. Each component style already sets the icon size
				appropriately. To manually scale an icon, use
				<code class="${hlmCode}">text-[length:--spacing(n)]</code>
				(e.g.
				<code class="${hlmCode}">text-[length:--spacing(5)]</code>
				) — this follows the spacing scale.
			</p>

			<spartan-page-bottom-nav>
				<spartan-page-bottom-nav-link href="dark-mode" label="Dark Mode" />
				<spartan-page-bottom-nav-link direction="previous" href="theming" label="Theming" />
			</spartan-page-bottom-nav>
		</section>

		<spartan-page-nav />
	`,
})
export default class StylesPage {
	protected readonly _styles = STYLES;
}
