// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(slider).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component, signal } from '@angular/core';import { HlmSliderComponent } from '@spartan-ng/helm/slider';@Component({
	selector: 'spartan-slider-preview',
	imports: [HlmSliderComponent],
	template: \`
		<hlm-slider [(value)]="value" />
	\`,
	styles: \`
		:host {
			display: block;
			width: 60%;
		}
	\`,
})
export class SliderPreviewComponent {
	public readonly value = signal(50);
}export const defaultSlider = \`
<hlm-slider />
\`;
`;
