// eslint-disable -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(spinner).preview.ts` file or the generator itself.
Run `pnpm run generate-snippets` to update this file.
*/

export const spinnerSizeCode = `
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { HlmSpinnerComponent } from '@spartan-ng/helm/spinner';

@Component({
	selector: 'spartan-spinner-size-preview',
	imports: [HlmSpinnerComponent],
	template: \`
		<div class="flex flex-col items-center gap-4">
			<hlm-spinner class="size-6" />
			<hlm-spinner class="size-8" />
			<hlm-spinner class="size-10" />
			<hlm-spinner class="size-12" />
		</div>
	\`,
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SpartanSpinnerSizePreviewComponent {}
`;

export const defaultCode = `
import { Component } from '@angular/core';
import { HlmSpinnerComponent } from '@spartan-ng/helm/spinner';

@Component({
	selector: 'spartan-spinner-preview',
	imports: [HlmSpinnerComponent],
	template: \`
		<hlm-spinner />
	\`,
})
export class SpinnerPreviewComponent {}
`;
