// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(select).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component } from '@angular/core';import { BrnSelectImports } from '@spartan-ng/brain/select';import { HlmSelectImports } from '@spartan-ng/helm/select';@Component({
	selector: 'spartan-select-preview',
	imports: [BrnSelectImports, HlmSelectImports],
	template: \`
		<brn-select class="inline-block" placeholder="Select an option">
			<hlm-select-trigger class="w-56">
				<hlm-select-value />
			</hlm-select-trigger>
			<hlm-select-content>
				<hlm-option value="Refresh">Refresh</hlm-option>
				<hlm-option value="Settings">Settings</hlm-option>
				<hlm-option value="Help">Help</hlm-option>
				<hlm-option value="Signout">Sign out</hlm-option>
			</hlm-select-content>
		</brn-select>
	\`,
})
export class SelectPreviewComponent {}export const defaultStyles = \`
@import '@angular/cdk/overlay-prebuilt.css';
\`;
`;
