// eslint-disable -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(textarea).preview.ts` file or the generator itself.
Run `pnpm run generate-snippets` to update this file.
*/

export const defaultCode = `
import { Component } from '@angular/core';
import { HlmInput } from '@spartan-ng/helm/input';

@Component({
	selector: 'spartan-textarea-preview',
	host: {
		class: 'w-full',
	},
	imports: [HlmInput],
	template: \`
		<textarea class="min-h-[80px] w-full" hlmInput placeholder="Type your message here."></textarea>
	\`,
})
export class TextAreaPreview {}
`;
