// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(textarea).preview.ts` file or the generator itself.
Run `pnpm run generate-snippets` to update this file.
*/

export const defaultCode = `
import { Component } from '@angular/core';
import { HlmInputDirective } from '@spartan-ng/helm/input';

@Component({
	selector: 'spartan-textarea-preview',
	host: {
		class: 'w-full',
	},
	imports: [HlmInputDirective],
	template: \`
		<textarea class="min-h-[80px] w-full" hlmInput placeholder="Type your message here."></textarea>
	\`,
})
export class TextAreaPreviewComponent {}

export const defaultCode = \`
import { Component } from '@angular/core';
import { HlmInputDirective } from '@spartan-ng/helm/input';

@Component({
  selector: 'spartan-textarea-preview',
imports: [HlmInputDirective],
  template: \\`  <textarea class="min-h-[80px] w-full" hlmInput placeholder="Type your message here."></textarea> \\`,
})
export class TextAreaPreviewComponent {}
\`;

export const defaultImports = \`
import { HlmInputDirective } from '@spartan-ng/helm/input';
\`;
export const defaultSkeleton = \`
<textarea hlmInput placeholder="Type your message here."></textarea>
\`;
`;


