// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(sonner).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component } from '@angular/core';import { HlmButtonDirective } from '@spartan-ng/helm/button';import { HlmToasterComponent } from '@spartan-ng/helm/sonner';import { toast } from 'ngx-sonner';@Component({
	selector: 'spartan-sonner-preview',
	imports: [HlmToasterComponent, HlmButtonDirective],
	template: \`
		<hlm-toaster />
		<button hlmBtn (click)="showToast()">Show Toast</button>
	\`,
})
export class SonnerPreviewComponent {
	showToast() {
		toast('Event has been created', {
			description: 'Sunday, December 03, 2023 at 9:00 AM',
			action: {
				label: 'Undo',
				onClick: () => console.log('Undo'),
			},
		});
	}
}
`;
