// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(switch).preview.ts` file or the generator itself.
Run `pnpm run generate-snippets` to update this file.
*/

export const defaultCode = `
import { Component } from '@angular/core';
import { HlmLabelDirective } from '@spartan-ng/helm/label';
import { HlmSwitchComponent } from '@spartan-ng/helm/switch';

@Component({
	selector: 'spartan-switch-preview',
	imports: [HlmLabelDirective, HlmSwitchComponent],
	template: \`
		<label class="flex items-center" hlmLabel>
			<hlm-switch class="mr-2" />
			Airplane mode
		</label>
	\`,
})
export class SwitchPreviewComponent {}

export const defaultCode = \`import { Component } from '@angular/core';
import { HlmLabelDirective } from '@spartan-ng/helm/label';
import { HlmSwitchComponent } from '@spartan-ng/helm/switch';

@Component({
	selector: 'spartan-switch-preview',
imports: [HlmLabelDirective, HlmSwitchComponent],
	template: \\`
		<label class="flex items-center" hlmLabel>
			<hlm-switch class="mr-2" />
			Airplane mode
		</label>
	\\`,
})
export class SwitchPreviewComponent {}
\`;

export const defaultImports = \`
import { HlmSwitchComponent } from '@spartan-ng/helm/switch';
\`;
export const defaultSkeleton = \`
<hlm-switch />
\`;
`;


