// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(button).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component } from '@angular/core';import { HlmButtonDirective } from '@spartan-ng/helm/button';@Component({
	selector: 'spartan-button-preview',
	imports: [HlmButtonDirective],
	template: \`
		<button hlmBtn>Button</button>
	\`,
})
export class ButtonPreviewComponent {}
`;
