// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(checkbox).preview.ts` file or the generator itself.
Run `pnpm run generate-snippets` to update this file.
*/

export const defaultCode = `
import { Component } from '@angular/core';import { HlmCheckboxComponent } from '@spartan-ng/helm/checkbox';import { HlmLabelDirective } from '@spartan-ng/helm/label';@Component({
	selector: 'spartan-checkbox-preview',
	imports: [HlmLabelDirective, HlmCheckboxComponent],
	template: \`
		<label class="flex items-center" hlmLabel>
			<hlm-checkbox class="mr-2" />
			Accept terms and conditions
		</label>
	\`,
})
export class CheckboxPreviewComponent {}
`;
