// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(label).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component } from '@angular/core';import { HlmInputDirective } from '@spartan-ng/helm/input';import { HlmLabelDirective } from '@spartan-ng/helm/label';@Component({
	selector: 'spartan-label-preview',
	imports: [HlmLabelDirective, HlmInputDirective],
	template: \`
		<label hlmLabel>
			E-Mail
			<input class="w-80" hlmInput type="email" placeholder="Email" />
		</label>
	\`,
})
export class LabelPreviewComponent {}
`;
