// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(toggle).preview.ts` file or the generator itself.
*/
export const defaultCode = `
import { Component } from '@angular/core';import { NgIcon, provideIcons } from '@ng-icons/core';import { lucideItalic } from '@ng-icons/lucide';import { BrnToggleDirective } from '@spartan-ng/brain/toggle';import { HlmIconDirective } from '@spartan-ng/helm/icon';import { HlmToggleDirective } from '@spartan-ng/helm/toggle';@Component({
	selector: 'spartan-toggle-preview',
	imports: [BrnToggleDirective, HlmToggleDirective, NgIcon, HlmIconDirective],
	providers: [provideIcons({ lucideItalic })],
	template: \`
		<button brnToggle hlm>
			<ng-icon hlm size="sm" name="lucideItalic" />
		</button>
	\`,
})
export class TogglePreviewComponent {}
`;
