import { Tree, joinPathFragments, logger } from '@nx/devkit';
import ts from 'typescript';
import { getVariableNameFromFilename } from './getVarNameFromFileName';

interface CodeSnippet {
	exampleName: string;
	code: string;
}

function getSourceFile(tree: Tree, filePath: string): ts.SourceFile | undefined {
	const content = tree.read(filePath, 'utf-8');
	if (!content) {
		logger.warn(`File not found or empty: ${filePath}`);
		return undefined;
	}

	const sourceFile = ts.createSourceFile(filePath, content, ts.ScriptTarget.Latest, true);
	return sourceFile;
}

function removeDefaultCodesAndGetContent(sourceFile: ts.SourceFile) {
	let content = '';
	ts.forEachChild(sourceFile, (node) => {
		const nodeText = node.getFullText(sourceFile);
		const pattern = /^export\s+const\s+\w+Code\s*=/;

		if (
			pattern.test(nodeText) ||
			nodeText.includes('export const defaultSkeleton =') ||
			nodeText.includes('export const defaultStyles =') ||
			nodeText.includes('export const defaultCode =') ||
			nodeText.includes('export const defaultImports =')
		) {
			return;
		}

		content += nodeText;
	});
	return content.trim();
}

export async function extractPrimitiveCodeGenerator(tree: Tree) {
	logger.info('Extract Primitive Code generator running...');

	const componentsDir = 'apps/app/src/app/pages/(components)/components';

	// Check if the base directory exists
	if (!tree.exists(componentsDir)) {
		logger.warn(`Base components directory not found: ${componentsDir}. Nothing to do.`);
		return;
	}

	const componentDirs = tree.children(componentsDir);
	logger.info(`Found ${componentDirs.length} component directories.`);

	for (const primitiveName of componentDirs) {
		const codeSnippets: CodeSnippet[] = [];
		const primitiveNameWithoutParentheses = primitiveName.replaceAll('(', '').replaceAll(')', '');
		const primitiveDir = joinPathFragments(componentsDir, primitiveName);
		if (tree.isFile(primitiveDir)) {
			continue;
		}

		const exampleFiles = tree.children(primitiveDir);
		exampleFiles.forEach((exampleFileName) => {
			if (!exampleFileName.endsWith('.preview.ts') && !exampleFileName.endsWith('.example.ts')) {
				return;
			}
			let exampleName = '';
			if (exampleFileName === primitiveNameWithoutParentheses + '.preview.ts') {
				exampleName = 'defaultCode';
			} else {
				exampleName = getVariableNameFromFilename(exampleFileName);
			}

			const fullFileName = joinPathFragments(primitiveDir, exampleFileName);
			const previewSourceFile = getSourceFile(tree, fullFileName);
			if (!previewSourceFile) {
				return; // Already logged by getSourceFile
			}

			const code = removeDefaultCodesAndGetContent(previewSourceFile);

			codeSnippets.push({
				exampleName,
				code,
			});
		});

		if (codeSnippets.length === 0) {
			logger.info(`No code snippets found for ${primitiveDir}. Skipping.`);
			continue;
		}

		const generatedFilePath = joinPathFragments(primitiveDir, `${primitiveNameWithoutParentheses}.generated.ts`);
		const generatedFileContent = `// eslint-disable -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the \`${primitiveName}.preview.ts\` file or the generator itself.
Run \`pnpm run generate-snippets\` to update this file.
*/

${codeSnippets
	.map((snippet) => {
		const replacedCode = snippet.code.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
		return `export const ${snippet.exampleName} = \`\n${replacedCode}\n\`;
`;
	})
	.join('\n')}

`;

		tree.write(generatedFilePath, generatedFileContent);
	}

	await formatFiles(tree);
}

export default extractPrimitiveCodeGenerator;
