// eslint-disable -- auto-generated
// @ts-nocheck -- auto-generated
// prettier-ignore -- auto-generated
/*
DO NOT EDIT THIS FILE!!
It is automatically generated by the extract-primitive-code generator.
Instead, edit the `(progress).preview.ts` file or the generator itself.
Run `pnpm run generate-snippets` to update this file.
*/

export const progressIndeterminateCode = `
import { Component } from '@angular/core';
import { BrnProgressComponent, BrnProgressIndicatorComponent } from '@spartan-ng/brain/progress';
import { HlmProgressDirective, HlmProgressIndicatorDirective } from '@spartan-ng/helm/progress';

@Component({
	selector: 'spartan-progress-indeterminate',
	imports: [BrnProgressComponent, BrnProgressIndicatorComponent, HlmProgressIndicatorDirective, HlmProgressDirective],
	template: \`
		<brn-progress class="w-80" hlm aria-labelledby="loading">
			<brn-progress-indicator hlm />
		</brn-progress>
	\`,
})
export class ProgressIndeterminatePreviewComponent {}

export const indeterminateCode = \`
import { Component } from '@angular/core';
import { BrnProgressComponent, BrnProgressIndicatorComponent } from '@spartan-ng/brain/progress';
import { HlmProgressDirective, HlmProgressIndicatorDirective } from '@spartan-ng/helm/progress';

@Component({
  selector: 'spartan-progress-indeterminate',
imports: [BrnProgressComponent, BrnProgressIndicatorComponent, HlmProgressIndicatorDirective, HlmProgressDirective],
  template: \\`
    <brn-progress hlm aria-labelledby='loading'>
      <brn-progress-indicator hlm />
    </brn-progress>
  \\`,
})
export class ProgressIndeterminatePreviewComponent {}
\`;
`;

export const defaultCode = `
import { Component, type OnInit } from '@angular/core';
import { BrnProgressComponent, BrnProgressIndicatorComponent } from '@spartan-ng/brain/progress';
import { HlmProgressDirective, HlmProgressIndicatorDirective } from '@spartan-ng/helm/progress';

@Component({
	selector: 'spartan-progress-preview',
	imports: [BrnProgressComponent, BrnProgressIndicatorComponent, HlmProgressIndicatorDirective, HlmProgressDirective],
	template: \`
		<brn-progress hlm class="w-80" aria-labelledby="loading" [value]="value">
			<brn-progress-indicator hlm />
		</brn-progress>
	\`,
})
export class ProgressPreviewComponent implements OnInit {
	public value = 15;

	ngOnInit() {
		setTimeout(() => (this.value = 65), 2000);
	}
}
`;


